services:
  api:
    build: .
    env_file: .env
    ports:
      - "5000:5000"
    depends_on:
      - mongo
      - redis
  mongo:
    image: mongo:6.0
    volumes:
      - mongo-data:/data/db
    restart: always
  redis:
    image: redis:6.2
    restart: always
    volumes:
      - redis-data:/data
volumes:
  mongo-data:
  redis-data: